// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using StartBack.Infrastructure.Persistence;

#nullable disable

namespace StartBack.Infrastructure.Migrations
{
    [DbContext(typeof(AemzDbContext))]
    [Migration("20250910055136_AddingNameAr")]
    partial class AddingNameAr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenuItemPermission", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RequiredPermissionsId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("MenuItemId", "RequiredPermissionsId");

                    b.HasIndex("RequiredPermissionsId");

                    b.ToTable("MenuItemPermission");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.Icon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("KEY");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ICONS");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<Guid?>("IconId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ICONID");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("KEY");

                    b.Property<int>("Order")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ORDER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PARENTID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TITLE");

                    b.Property<string>("TitleAr")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TITLEAR");

                    b.Property<string>("TitleEn")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TITLEEN");

                    b.Property<string>("Url")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("MENUITEMS");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CODE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PERMISSIONS");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("EXPIRESAT");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("REPLACEDBYTOKEN");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("REVOKEDAT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)")
                        .HasColumnName("TOKEN");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("REFRESHTOKENS");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Category")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETEDAT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETEDBY");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("DetailColumn")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DETAILCOLUMN");

                    b.Property<int?>("DetailId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DETAILID");

                    b.Property<bool>("HasDetail")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("HASDETAIL");

                    b.Property<bool>("Hide")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("HIDE");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISDELETED");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAMEAR");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAMEEN");

                    b.Property<string>("Path")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PATH");

                    b.Property<string>("Query")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("QUERY");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATEDAT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATEDBY");

                    b.HasKey("Id");

                    b.ToTable("REPORTS");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.ReportColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Field")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FIELD");

                    b.Property<string>("Filter")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FILTER");

                    b.Property<bool>("FloatingFilter")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FLOATINGFILTER");

                    b.Property<string>("HeaderName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("HEADERNAME");

                    b.Property<bool>("Hide")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("HIDE");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISMASTER");

                    b.Property<int>("ReportId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REPORTID");

                    b.Property<bool>("Resizable")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("RESIZABLE");

                    b.Property<bool>("RowGroup")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ROWGROUP");

                    b.Property<int>("Sort")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SORT");

                    b.Property<bool>("Sortable")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("SORTABLE");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("REPORTCOLUMNS");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.ReportParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DATATYPE");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DEFAULTVALUE");

                    b.Property<string>("DisplayName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISREQUIRED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME");

                    b.Property<string>("ParameterType")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PARAMETERTYPE");

                    b.Property<string>("QueryForDropdown")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("QUERYFORDROPDOWN");

                    b.Property<int>("ReportId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REPORTID");

                    b.Property<int?>("Sort")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SORT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("REPORTPARAMETERS");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("DefaultPageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DEFAULTPAGEURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DISPLAYNAME");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PASSWORDHASH");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("PROFILEIMAGEURL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("MenuItemPermission", b =>
                {
                    b.HasOne("StartBack.Domain.Entities.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StartBack.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("RequiredPermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("StartBack.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StartBack.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("StartBack.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StartBack.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StartBack.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("StartBack.Domain.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StartBack.Domain.Entities.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.ReportColumn", b =>
                {
                    b.HasOne("StartBack.Domain.Entities.Report", "Report")
                        .WithMany("Columns")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.ReportParameter", b =>
                {
                    b.HasOne("StartBack.Domain.Entities.Report", "Report")
                        .WithMany("Parameters")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("StartBack.Domain.Entities.Report", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
